name = "DiscreteElasticRods"
uuid = "f4f2e712-d3ec-4060-864c-7a80dfe5a9a5"
authors = ["James Gabbard"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
